.phony: thread 02 03 04 05 06 p_n_c

thread : thread.cpp
	g++ -std=c++17 thread.cpp -lpthread

02 : thread02.cpp
	g++ -std=c++17 thread02.cpp -lpthread

03 : thread03.cpp
	g++ -std=c++17 thread03.cpp -lpthread

04 : thread04.cpp
	g++ -std=c++17 thread04.cpp -lpthread

05 : thread05.cpp
	g++ -std=c++17 thread05.cpp -lpthread

06 : thread06.cpp
	g++ -std=c++17 thread06.cpp -lpthread

07 : thread07.cpp
	g++ -std=c++17 thread07.cpp -lpthread

p_n_c : p_n_c.cpp
	g++ -std=c++17 p_n_c.cpp -lpthread



	