.phony: 01

01 : thread01.cpp
	g++ -std=c++17 thread01.cpp -lpthread

02 : thread02.cpp
	g++ -std=c++17 thread02.cpp -lpthread

03 : thread03.cpp
	g++ -std=c++17 thread03.cpp -lpthread

04 : thread04.cpp
	g++ -std=c++17 thread04.cpp -lpthread

05 : thread05.cpp
	g++ -std=c++17 thread05.cpp -lpthread



	