bubble : bubble_sort.cpp
	g++ bubble_sort.cpp -o run

selection: selection_sort.cpp
	g++ selection_sort.cpp -o run

insertion: insertion_sort.cpp
	g++ insertion_sort.cpp -o run

quick: quick_sort.cpp
	g++ quick_sort.cpp -o run